app:
  name: golang e commerce
  host: localhost
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: ""
  dbname: simple_ecommerce
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  dbname: 0

jwt:
  secret_key: ""

logger:
  level: 4
  file_path: logs/app.log

storage:
  base_path: "./public"
  public_path: "/public"